---
language: node_js

services:
  - docker

install:
  - docker build . -t docker.io/cronym/fp-discord-bot:${TRAVIS_BUILD_NUMBER}

jobs:
  include:
    - stage: test
      script: ./scripts/tests.sh
    - stage: deploy
      script: ./scripts/deploy.sh
      # if: branch = master AND tag IS present
      if: branch = master

script: ./scripts/docker-tag.sh
