language: node_js

services:
  - docker

before_script:
  - version=$TRAVIS_PULL_REQUEST

install:
  - docker build . -t docker.io/cronym/fp-discord-bot:${TRAVIS_PULL_REQUEST}

script: ./script/docker-tag.sh
